const RECEIVE_CAR_MARKET = "RECEIVE_CAR_MARKET";
const FILTER_AFTER_SEARCH_FIELD = "FILTER_AFTER_SEARCH_FIELD";
const FILTER_AFTER_BRAND_DROPDOWN = "FILTER_AFTER_BRAND_DROPDOWN";
const FILTER_AFTER_MODEL_DROPDOWN = "FILTER_AFTER_MODEL_DROPDOWN";
const ADD_REMOVE_CART_ITEM = "ADD_REMOVE_CART_ITEM";
const COMPLETE_TRANSACTION = "COMPLETE_TRANSACTION";

export { RECEIVE_CAR_MARKET,
         FILTER_AFTER_SEARCH_FIELD,
         FILTER_AFTER_BRAND_DROPDOWN,
         FILTER_AFTER_MODEL_DROPDOWN,
         ADD_REMOVE_CART_ITEM,
         COMPLETE_TRANSACTION };
