export const AJAX_CALL_BEGIN = "AJAX_CALL_BEGIN";
export const CHECK_CAR_MODEL = "CHECK_CAR_MODEL";
export const CHECKOUT_CAR_MODEL = "CHECKOUT_CAR_MODEL";
export const AJAX_CALL_SUCCESS = "AJAX_CALL_SUCCESS";
