// POSTS
export const POSTS = {
    REQUEST_POSTS: 'REQUEST_POSTS',
    RECEIVE_POSTS: 'RECEIVE_POSTS'
};

// SEARCH
export const SEARCH = {
    FILTER_AFTER_SEARCH_FIELD: 'FILTER_AFTER_SEARCH_FIELD',
    FILTER_AFTER_BRAND_DROPDOWN: 'FILTER_AFTER_BRAND_DROPDOWN',
    FILTER_AFTER_MODEL_DROPDOWN: 'FILTER_AFTER_MODEL_DROPDOWN'
};

// TRANSACTIONS
export const TRANSACTIONS = {
    TOGGLE_VEHICLE: 'TOGGLE_VEHICLE',
    TOGGLE_CART: 'TOGGLE_CART',
    COMPLETE_TRANSACTION: 'COMPLETE_TRANSACTION'
};
